### ISSUE TITLE
How to install all requirement

### ISSUE THREAD

**Issue by adiramardiani** [loicmarie/sign-language-alphabet-recognizer#1]
Hello brother, btw thanks for this source

After I install Python3, I confused to install the requirement

Can you add requirement.txt so we can install with `pip3 install -r requirements.txt` ?

I don't know what specific version used, for example in requirements.txt contain : 

```
numpy==1.13.0
scikit_learn==0.18.1
scipy==0.19.0
```

Or you have other way to install the requirement

**Comment by loicmarie** [comment]
In 298d71a I added requirements.txt and Dockerfile that can be useful. If you have other difficulties please let me know, I will reopen the issue. Thank you for your interest !

**Comment by adiramardiani** [comment]
Thanks, requirements installed and your application working well 👍 

I train your dataset about 16hour :D 

I'm very interest about computer vision, but I'm newbe in programmer and all the cv teory
I have a question, why the dataset is 3000 image, do you have a formula or something else ?
How to create the dataset/image ? because when I run it it's like a cut movement per 1000 images

Thanks, Or maybe I should ask this in an email

**Comment by loicmarie** [comment]
I'm pleased it works fine now 👍, I'm also learning about computer vision.

I have a script for creating my own dataset using webcam, I will publish it soon. The cut movement is due to the process time of the classifier, which depends on your computer performances and Tensorflow install (takes ~60ms/compute for me). The model used is not the fastest and I will also change it soon.

Currently, I am working on an other project that will be linked to this one (see hands-detection in my personal repos) so I will probably not push any changes on SLR recognizer this week, but do not hesitate to follow this repo to be alerted when it happens.

**Comment by adiramardiani** [comment]
Oke, Happy to waiting about integrating to other project, thanks brother 👍

**Comment by mediocre329** [comment]
can i run this using pycharm? theres an error says that i have a numpy and tensorflow compatability problem.  And also can raspberry Pi run this program? because we have a project on SLR that uses raspi
