### ISSUE TITLE
How I can plot the grey window? It is not in classify_webcam.py.

### ISSUE THREAD

**Issue by LMdeLiangMi** [loicmarie/sign-language-alphabet-recognizer#2]
Are they grey picture txt files in boottlenecks folder？

In classify.py: image_data = tf.gfile.FastGFile(image_path, 'rb').read()

In classify_webcam.py: image_data = cv2.imencode('.jpg', img_cropped)[1].tostring()

Are they the same?
How can I plot these image_data?

**Comment by loicmarie** [comment]
These images were preprocessed using MOG Background Substraction,  but since the model has changed (and use exclusively cropped-images without preprocessing) I removed it from the notebook and generated new data in consequence. I will fix classify_webcam omissions soon and will make a new video with better results but I'm still working on it.
Thank you for your interest
